name: evaluation
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl:
  dio:
  pretty_dio_logger:
  flutter_riverpod:
  shared_preferences:
  google_fonts:
  internet_connection_checker:
  cupertino_icons: ^1.0.2
  flutter_animate:
  json_annotation:
  dartz: ^0.10.1
  responsive_sizer: ^3.1.1
  flutter_native_splash: ^2.0.0
  easy_localization: ^3.0.7
  material_symbols_icons: ^4.2762.0
  bottom_sheet_scaffold: ^0.1.9
  smooth_page_indicator: ^1.2.0+3
  pin_code_fields: ^8.0.1
  local_auth: ^2.3.0
  nfc_manager: ^3.5.0
  image_picker: ^1.1.2
  image: ^4.3.0
  flutter_svg: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_gen_runner:
  json_serializable: ^6.7.1

flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/apercu_regular.otf
          weight: 400
        - asset: assets/fonts/apercu_bold.otf
          weight: 700
