import 'app_theme.dart';
import 'package:flutter/material.dart';

extension AppColorScheme on AppTheme {
  ColorScheme get colorScheme {
    switch (this) {
      case AppTheme.light:
        return _lightColorScheme;
      case AppTheme.dark:
        return _darkColorScheme;
    }
  }

  ColorScheme get _lightColorScheme => const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF2F4656),
      onPrimary: Color(0xFFEBEBEB),
      primaryContainer: Color(0xFFD3E3FF),
      onPrimaryContainer: Color(0xFF001C39),
      secondary: Color(0xFF545F71),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD8E3F8),
      onSecondaryContainer: Color(0xFF111C2B),
      tertiary: Color(0xFF6D5677),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF6D9FF),
      onTertiaryContainer: Color(0xFF261430),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF93000A),
      primaryFixed: Color(0xFFD3E3FF),
      primaryFixedDim: Color(0xFFA4C9FE),
      onPrimaryFixed: Color(0xFF001C39),
      onPrimaryFixedVariant: Color(0xFF204876),
      secondaryFixed: Color(0xFFD8E3F8),
      secondaryFixedDim: Color(0xFFBCC7DB),
      onSecondaryFixed: Color(0xFF111C2B),
      onSecondaryFixedVariant: Color(0xFF3C4758),
      tertiaryFixed: Color(0xFFF6D9FF),
      tertiaryFixedDim: Color(0xFFD9BDE3),
      onTertiaryFixed: Color(0xFF261430),
      onTertiaryFixedVariant: Color(0xFF543F5E),
      surfaceDim: Color(0xFFD9DAE0),
      surface: Color(0xFF30CC3A),
      surfaceBright: Color(0xFFF8F9FF),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF2F3FA),
      surfaceContainer: Color(0xFFEDEDF4),
      surfaceContainerHigh: Color(0xFFE7E8EE),
      surfaceContainerHighest: Color(0xFFE1E2E9),
      onSurface: Color(0xFF191C20),
      onSurfaceVariant: Color(0xFF191C20),
      outline: Color(0xFF73777F),
      outlineVariant: Color(0xFFC3C6CF),
      inverseSurface: Color(0xFF2E3035),
      onInverseSurface: Color(0xFFEFF0F7),
      inversePrimary: Color(0xFFA4C9FE),
      scrim: Color(0xFF000000),
      shadow: Color(0xFF000000));

  ColorScheme get _darkColorScheme => const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFA4C9FE),
      onPrimary: Color(0xFF00315C),
      primaryContainer: Color(0xFF204876),
      onPrimaryContainer: Color(0xFFD3E3FF),
      secondary: Color(0xFFBCC7DB),
      onSecondary: Color(0xFF263141),
      secondaryContainer: Color(0xFF3C4758),
      onSecondaryContainer: Color(0xFFD8E3F8),
      tertiary: Color(0xFFD9BDE3),
      onTertiary: Color(0xFF3D2946),
      tertiaryContainer: Color(0xFF543F5E),
      onTertiaryContainer: Color(0xFFF6D9FF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      primaryFixed: Color(0xFFD3E3FF),
      primaryFixedDim: Color(0xFFA4C9FE),
      onPrimaryFixed: Color(0xFF001C39),
      onPrimaryFixedVariant: Color(0xFF204876),
      secondaryFixed: Color(0xFFD8E3F8),
      secondaryFixedDim: Color(0xFFBCC7DB),
      onSecondaryFixed: Color(0xFF111C2B),
      onSecondaryFixedVariant: Color(0xFF3C4758),
      tertiaryFixed: Color(0xFFF6D9FF),
      tertiaryFixedDim: Color(0xFFD9BDE3),
      onTertiaryFixed: Color(0xFF261430),
      onTertiaryFixedVariant: Color(0xFF543F5E),
      surfaceDim: Color(0xFF111318),
      surface: Color(0xFF111318),
      surfaceBright: Color(0xFF37393E),
      surfaceContainerLowest: Color(0xFF0C0E13),
      surfaceContainerLow: Color(0xFF191C20),
      surfaceContainer: Color(0xFF1D2024),
      surfaceContainerHigh: Color(0xFF272A2F),
      surfaceContainerHighest: Color(0xFF272A2F),
      onSurface: Color(0xFFE1E2E9),
      onSurfaceVariant: Color(0xFFC3C6CF),
      outline: Color(0xFF8D9199),
      outlineVariant: Color(0xFF43474E),
      inverseSurface: Color(0xFFE1E2E9),
      onInverseSurface: Color(0xFF2E3035),
      inversePrimary: Color(0xFF3A608F),
      scrim: Color(0xFF000000),
      shadow: Color(0xFF000000));
}
